language: java
sudo: false
jdk :
  - oraclejdk8

env:
  global:
    - secure: "aPPmK6hLgszgyryvXRRCcLbjMTqji0sh0bnwCDKzGhTF4tt735P3SMAUHFxR5gsSQToOw65KXTgNdL7OaJLyneeRUICFcIDZUwMVd0RJOM4VN3v3bCJxlmdTpr8qNcNt592reSYvHhBWlp/L8+D+iVWAX+vZH6mEAIJtxAEEPyV+noS3wa3grEeRu6eS9nZt3CMu6hZFumRdg6mWsUBfZFWf8qDJn3EFBfSgLmmGi9E6H6YCFvt2+pLasAEkjaxbZYieuYURq2Haa7ADJF6p775W8dr7enhS5GzjmwN6CuWkpD16yOVKV8UVKNsCZ8uLoLn65GPP22TmTwXWsD2kUtfViYSrqchOCYagvddMWpDfk+jQtNp2TbSdiPMlibJ2sfikt+GWd6GZwpkg5Z+rL/GfxBejB3KooHfdyBDuVDmXVsShGueu6G3PYdlLSLfSAaIaTq8PxXqkd0+hnHXP+ujQVhc2IpUBjmLMMcla4yDkZcuv8uWwfbN905AY8XQjuVVT5zurf74gXXx7b+wDFkSnmyF6GGFlOnrDrsKjkOL2bBP5sgyDDwr3mqzsoWtxXCdv3nIaqwIFHQWj1Yh41ioMOVVQV8BvK6TgllJMuCnfHkUPPSmm54Viyzb0JO8laL5JwjfT4XvMWGMFOgZmof2lodhLjarKsMIIzZmbV8g="
    - secure: "N2DOuvkPLFndgDF8Kw5e7f0a9raToD4JPmhz14sgrzJe2QEAMraDuxeBGyBt+9QFdx42xyLesCXQNPJuBtuMuAoxQZ6HQk/9NMqXR16qhs6MnlwHsuiIzycTfpCF+t/kCr+xsV1BfbqFAy5uQkeKnNR2lCwT7Pqfx4zrueXXvibH+A1UhG7HGaf+Hop4qj9JfRySIdmMPmwtWtsr44jYBp7qQlIDO9MY+ymuiapBGkbCQzJKrOXBmnY41Ch9O4XnTnUQWSLikEJINgaTpERA6dlzjx75Vj5E5XLQW2sDoZRp/KOymEIIKNbhVHU99ko+maf4avUxmAaTAGvofIdq+eJMtPrdkd0uJnplVii8k/ZifFseIRHp9pwc6XoRZtbQesjd/gwz7JmyJFuTErFYUShVXBXoaN5C/tyKMbBD7jQJWZauWgv6SMGKxFnT7OFQanS5OQOXR4FV06uyi2C0qVhr3A/x85rhOwmV3mTLCdeIgHFnYf409P2TQByN2t1YOGOdNBVMEX68XwXa0/5QFjf+sVh2mynBne6AfdFjoa/FqFCzUmDcm9OvGXshIR7bukh48Uyoax/WwBU4Fk+D9jDSq9M0CIu8vOz+wF8pbYA/99ucdvTCE5rtmMCe2fJcNh1L4i+z+SUjEFcwEwdgP8P2DUUnlaC0xSsbbpSfSCQ="

addons:
  sonarqube: true

script:
  - echo $SONAR_TOKEN
  - mvn clean install -Dmaven.test.failure.ignore=true -P development

after_success:
  - if [[ -n $TRAVIS_PULL_REQUEST && $TRAVIS_PULL_REQUEST != "false" ]]; then mvn --batch-mode --errors --show-version sonar:sonar -Dsonar.analysis.mode=preview  -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN  -Dsonar.github.oauth=$SONAR_GITHUB_TOKEN  -Dsonar.github.pullRequest=$TRAVIS_PULL_REQUEST  -Dsonar.github.repository=$TRAVIS_REPO_SLUG; else mvn sonar:sonar; fi
  - bash <(curl -s https://codecov.io/bash)

